version: '3'


# docker run -d --name juslitedb -p 9200:9200 -p 9300:9300 -e "discovery.type=single-node" --memory="1g" elasticsearch:7.14.2

services:
  juslite_elastic:
    image: elasticsearch:7.14.2
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms1024m -Xmx1024m"
    # command: command
    volumes:
      - juslite_data:/usr/share/elasticsearch/data
  juslite_api:
    build: ./api

volumes:
  juslite_data:
