version: '3'


# docker run -d --name juslitedb -p 9200:9200 -p 9300:9300 -e "discovery.type=single-node" --memory="1g" elasticsearch:7.14.2

services:
  juslite_elastic:
    image: elasticsearch:7.14.2
    container_name: juslite_elastic
    ports:
      - 9200:9200
      - 9300:9300
    environment:
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms1024m -Xmx1024m"
    volumes:
      - juslite_data:/usr/share/elasticsearch/data
    restart: always

  juslite_api:
    build: ./api
    container_name: juslite_api
    expose:
      - 3001
    volumes:
      - ./api:/app
    restart: always

  juslite_crawlers:
    build: ./crawlers
    container_name: juslite_crawlers
    volumes:
      - ./crawlers:/app

  juslite_page:
    build: ./page
    container_name: juslite_page
    expose:
      - 3000
    volumes:
      - ./page:/app
      - /app/node_modules
    restart: always

  juslite_proxy:
    image: nginx:alpine
    container_name: juslite_proxy
    ports:
        - 80:80
        - 443:443
    volumes:
        - ./proxy:/etc/nginx/conf.d
    restart: always

volumes:
  juslite_data:
