TST_DICT = {
    "AA": "Ação Anulatória",
    "AC": "Ação Cautelar",
    "ACP": "Ação Civil Pública",
    "ACCS": "Ação de Cobrança de Contribuição Sindical",
    "ACHP": "Ação de Cobrança de Honorários Profissionais",
    "ACPG": "Ação de Consignação em Pagamento",
    "ACUMP": "Ação de Cumprimento",
    "AEX": "Ação de Execução",
    "AEXTAC": "Ação de Execução de Termo de Ajuste de Conduta Firmado pelo MPT",
    "AEXTCP": "Ação de Execução de Termo de Conciliação da Comissão de Conciliação Prévia",
    "AEXF": "Ação de Execução Fiscal",
    "AIND": "Ação de Indenização",
    "AINDAT": "Ação de Indenização por Acidente de Trabalho",
    "APC": "Ação de Prestação de Contas",
    "ARI": "Ação de Repetição de Indébito",
    "ARS": "Ação de Representação Sindical",
    "AD": "Ação Declaratória",
    "AM": "Ação Monitória",
    "APO": "Ação Possessória",
    "AR": "Ação Rescisória",
    "A": "Agravo",
    "AI": "Agravo de Instrumento",
    "AIAP": "Agravo de Instrumento em Agravo de Petição",
    "AIRR": "Agravo de Instrumento em Recurso de Revista",
    "AIRMA": "Agravo de Instrumento em Recurso em Matéria Administrativa",
    "AIRE": "Agravo de Instrumento em Recurso Extraordinário",
    "AIRO": "Agravo de Instrumento em Recurso Ordinário",
    "AP": "Agravo de Petição",
    "AG": "Agravo Regimental",
    "AGPET": "Agravo Regimental em Petição",
    "APEN": "Aplicação de Penalidade",
    "AINC": "Argüição de Inconstitucionalidade",
    "CO": "Carta de Ordem",
    "CS": "Carta de Sentença",
    "CP": "Carta Precatória",
    "CPEX": "Carta Precatória Executória",
    "CR": "Carta Rogatória",
    "CC": "Conflito de Competência",
    "CPJ": "Contraprotesto Judicial",
    "DC": "Dissídio Coletivo",
    "ES": "Efeito Suspensivo",
    "E": "Embargos",
    "ED": "Embargos de Declaração",
    "ET": "Embargos de Terceiro",
    "EI": "Embargos Infringentes",
    "EXIMP": "Exceção de Impedimento",
    "EXINC": "Exceção de Incompetência",
    "EXSUSP": "Exceção de Suspeição",
    "HC": "Habeas Corpus",
    "HD": "Habeas Data",
    "IVC": "Impugnação ao Valor da Causa",
    "IF": "Incidente de Falsidade",
    "IUJ": "Incidente de Uniformização de Jusrisprudência",
    "IAFG": "Inquérito para Apuração de Falta Grave",
    "IT": "Intervenção de Terceiros",
    "JJ": "Justificação Judicial",
    "MS": "Mandado de Segurança",
    "MA": "Matéria Administrativa",
    "PP": "Pedido de Providência",
    "PRVC": "Pedido de Revisão do Valor da Causa",
    "PREC": "Precatório",
    "PAD": "Processo Administrativo Disciplinar",
    "PJ": "Protesto Judicial",
    "R": "Reclamação",
    "RC": "Reclamação Correicional",
    "RT": "Reclamação Trabalhista",
    "RA": "Recurso Administrativo",
    "RM": "Recurso de Multa",
    "RR": "Recurso de Revista",
    "RMA": "Recurso em Matéria Administrativa",
    "RE": "Recurso Extraordinário",
    "RO": "Recurso Ordinário",
    "RXOF": "Remessa de Ofício",
    "RXOF E AP": "Remessa de Ofício e Agravo de Petição",
    "RXOF E RO": "Remessa de Ofício e Recurso Ordinário",
    "RP": "Representação",
    "RPV": "Requisição de Pequeno Valor",
    "RAUT": "Restauração de Autos",
    "SL": "Suspensão de Liminar",
    "SS": "Suspensão de Segurança",
    "ADIV ": "Ação Diversa",
}
